PACKAGES = \
	extern\boost \
	extern\pugixml \
	uhal 

VIRTUAL_PACKAGES = $(addsuffix \.virtual.Makefile,${PACKAGES})

FLAGS = $(ifeq $(MAKEFLAGS) "","",-$(MAKEFLAGS))

TARGETS=clean rpm build all

.PHONY: $(TARGETS)
default: build

$(TARGETS): ${VIRTUAL_PACKAGES}

${VIRTUAL_PACKAGES}:
	${MAKE} -f Makefile.win ${FLAGS} -C $(@D) $(MAKECMDGOALS)
