## Sconstruct file for the IPbusClient package
#	@author Andrew W. Rose
#	@author Simon Fayer
#	@date 2010

## Get the standard boost environment
env = SConscript('../.SConscript.cactus')
Export('env')

SConscript('SConscript')
