env = Environment()

env.Append( CXXFLAGS=['-Wall'])
env.Append( CPPPATH= ['/opt/local/include','../uhal/include'])

env.Append( LIBPATH = ['/opt/local/lib','../uhal/lib'])
env.Append( LIBS = ['boost_unit_test_framework','boost_program_options','uhal'])

env.Program('examples','src/common/examples.cpp')

env.Program('test_testing_tools', 'src/common/test_testing_tools.cpp')
env.Program('test_uhal', 'src/common/test_uhal.cpp')
#env.Program('test_clientinterface', 'src/common/test_clientinterface.cpp')
#env.Program('test_performance','src/common/test_performance.cpp')

