## Sconstruct file for the IPbusClient package
#	@author Andrew W. Rose
#	@author Simon Fayer
#	@date 2010

## Import the environment from the SConstruct File
Import('env')

localenv = env.Clone()
localenv.VariantDir( localenv.SrcBuildPath , 'src/common' , duplicate=0 )

## Add default libs
localenv.Append( 
	LIBS = [ 'uhal' , 'grammars' , 'log' ] 

)  

## Compile the IPbusClient Unit Test as an executable
localenv.Program( 
	target = localenv.SrcBuildPath+'/test_uhal', 
	source = [ localenv.SrcBuildPath+'/test_uhal.cpp' ]
)

localenv.Program( 
	target = localenv.SrcBuildPath+'/test_timing', 
	source = [ localenv.SrcBuildPath+'/test_timing.cpp' ]
)

localenv.Program( 
	target = localenv.SrcBuildPath+'/DummyHardwareUdp', 
	source = [ localenv.SrcBuildPath+'/DummyHardwareUdp.cpp' ]
)

localenv.Program( 
	target = localenv.SrcBuildPath+'/DummyHardwareTcp', 
	source = [ localenv.SrcBuildPath+'/DummyHardwareTcp.cpp' ]
)