## Sconstruct file for the IPbusClient package
#	@author Andrew W. Rose
#	@author Simon Fayer
#	@date 2010

## Import the environment from the SConstruct File
Import('env')

localenv = env.Clone()
localenv.VariantDir( localenv.BuildPath+'/src/common' , 'src/common' , duplicate=0 )

## Add default libs
localenv.Append( 
	LIBS = [  ] 
)  

## Build IPbusClient as a shared library
lib = localenv.SharedLibrary( 
	target = localenv.LibPath+'/BoostSpiritGrammars', 
	source = [ Glob(localenv.BuildPath+'/src/common/*.cpp') ]
)

# Install the libraries
localenv.Install( localenv.InstallPath , lib )
localenv.Alias( 'install', localenv.InstallPath )

