## Sconstruct file for the IPbusClient package
#	@author Andrew W. Rose
#	@author Simon Fayer
#	@date 2010

## Import the environment from the SConstruct File
import os
Import('env')

localenv = env.Clone()
localenv.VariantDir( localenv.BuildPath+'/src/common' , 'src/common' , duplicate=0 )

## Add default libs
localenv.Append( 
	LIBS = [  'BoostSpiritGrammars' ]
)

## Build IPbusClient as a shared library
lib = localenv.SharedLibrary( 
	target = localenv.LibPath+'/uhal', 
	source = [ Glob(localenv.BuildPath+'/src/common/*.cpp') ]
)

logging_lib = localenv.SharedLibrary( 
	target = localenv.LibPath+'/uhal.pantheios.be.colour', 
	source = [ localenv.BuildPath+'/src/common/pantheios.be.colour.cc' ]
)

# Install the libraries
localenv.Install( localenv.InstallPath , [ lib , logging_lib ] )
localenv.Alias( 'install', localenv.InstallPath )


