#!/bin/env bash

#############################################################################################
# For opening a remote-shell to the Control Hub node, to allow interactive debugging, etc.
#
# Robert Frazier, June 2012
#############################################################################################

# Get current working directory
DIR="$( cd "$( dirname "$0" )" && pwd )"


# See if the controlhub is up
${DIR}/controlhub_status > /dev/null
CONTROLHUBSTATUS=$?

if [ $CONTROLHUBSTATUS = 0 ]; then
  # Open a remote shell to the controlhub node.
  #   -- $RANDOM is used to give the startup shell a random node name in order
  #      to prevent name clashes if more that one remote shell is open.
  ${DIR}/erl +B -sname $RANDOM -setcookie ch_cookie -remsh controlhub@`hostname -s` -hidden
else
  echo "Control Hub is down"
  exit 1
fi
