#!/usr/bin/python
"""
usage: ipbus_addr_map.py [options] <address_table.xml>

Extracts the different IPBus maps associated to an address table. That is, for each bus, it retrieves the space separated list of:
* slave number           [dec]
* slave name             [string]
* slace address          [hex]
* number of address bits [dec]

where:
  <address_table.xml>    address table in uHAL format

options:
  -v, --verbose          verbose
"""
from uhal.tools.ipbus_addr_map import ipbus_addr_map,hex32
import getopt
import sys

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "vh", ["verbose","help"])
    except getopt.GetoptError, err:
        print __doc__
        sys.exit(2)

    verbose = False
    for o, a in opts:
        if o in ("-v", "--verbose"):
            verbose = True
        if o in ("-h", "--help"):
            print __doc__
            sys.exit(0)
            
    if len(args) != 1:
        sys.stderr.write("ERROR: Missing <address_table.xml>\n")
        print __doc__
        sys.exit(1)


    try:
        m = ipbus_addr_map(args[0],verbose)
    except Exception,e:
        sys.stderr.write("ERROR: %s\n" % str(e))
        sys.exit(1)
        
    for bus,slaves in m:
        print "#%s bus address map" % bus
        print "#slave_num\tslave_id\taddress[hex]\taddress_width[bits]"
        for n,(slave,addr,width) in enumerate(slaves):
            print "%d\t%s\t%s\t%s" % (n,slave,hex32(addr),width)

        print "\n\n"
    
if __name__ == '__main__':
    main()
