#!/bin/env escript
%% -*- erlang -*-
%%! -sname tempshellstatus -setcookie ch_cookie -hidden

%########################################################################
% Prints the status of the Control Hub and returns a corresponding code:
%   * Return code is 0 if running.
%   * Return code is 1 if down.
%
% Robert Frazier, June 2012
%########################################################################

main(_Ignore) ->
  {ok, Hostname} = inet:gethostname(),
  Node = list_to_atom("controlhub@" ++ Hostname),
  ReturnCode = case net_adm:ping(Node) of
                   pang ->
                       io:format("Control Hub is down~n"),
                       1;
                   pong ->
                       io:format("Control Hub is up~n"),
                       0
               end,
  halt(ReturnCode).
