#!/opt/cactus/bin/escript
%% -*- erlang -*-
%%! -sname tempshellappmon -setcookie ch_cookie

%########################################################################
% If the Control Hub is running, it will open up appmon. Ctrl-c to quit.
%   * Return code is 0 if the Control Hub is not running.
%
% Robert Frazier, January 2013
%########################################################################

main(_Ignore) ->
  {ok, Hostname} = inet:gethostname(),
  Node = list_to_atom("controlhub@" ++ Hostname),
  ReturnCode = case net_adm:ping(Node) of
                   pang ->
                       io:format("Control Hub is down - no point opening appmon!~n"),
                       1;
                   pong ->
                       io:format("Control Hub is up - opening appmon...~nPress ctrl-c to quit.~n"),
                       appmon:start(),
                       timer:sleep(infinity),  % Better way of doing this?...
                       0
               end,
  halt(ReturnCode).
