## Sconstruct file for the CACTUS project
#	@author Andrew W. Rose
#	@author Simon Fayer
#	@date 2010

## Get the standard cactus environment
env = SConscript( "./.SConscript.uhal" )

Export('env')

## Build the relevant directories
SConscript( [ 'log/SConscript' , 'BoostSpiritGrammars/SConscript' , 'uhal/SConscript' , 'tests/SConscript'] )



