BUILD_HOME = $(shell pwd)/../..

include $(BUILD_HOME)/config/Makefile.macros
include #(BUILD_HOME)/config/Makefile.macros

Project = uhal/tools
Package = uhal/tools
PackagePath = $(CACTUS_RPM_ROOT)/${Package}
PackageName = cactuscore-uhal-tools
PackageURL = https://ipbus.web.cern.ch/ipbus

Packager = Kristian Harder, Dave Newbold, Tom Williams

PACKAGE_VER_MAJOR = 2
PACKAGE_VER_MINOR = 5
PACKAGE_VER_PATCH = 1
PACKAGE_RELEASE = 1



.PHONY: _all build clean
clean: ;
_all: ;
build: ;

BuildDebuginfoRPM = 0

include $(BUILD_HOME)/uhal/config/mfRPMRules.mk