---------------------------------------------------------------------------------
-- Address decode logic for IPbus fabric.
--
-- This file has been AUTOGENERATED from the address table - do not
-- hand edit.
--
-- We assume the synthesis tool is clever enough to recognise
-- exclusive conditions in the if statement.
---------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_addr_table_c is

-- START automatically generated VHDL (Thu Jun 15 14:28:34 2023)
  constant IPBUS_SEL_WIDTH: positive := 1;
-- END automatically generated VHDL

  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_addr_table_c(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Thu Jun 15 14:28:34 2023)
  constant N_SLAVES: integer := 0;
-- END automatically generated VHDL

end ipbus_decode_addr_table_c;

package body ipbus_decode_addr_table_c is

  function ipbus_sel_addr_table_c(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Thu Jun 15 14:28:34 2023)
    sel := ipbus_sel_t(to_unsigned(0, IPBUS_SEL_WIDTH));
-- END automatically generated VHDL

    return sel;

  end function ipbus_sel_addr_table_c;

end ipbus_decode_addr_table_c;

---------------------------------------------------------------------------------
